#!/usr/bin/env bash
# configures a new Ubuntu machine to respecting requirements
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo Holberton School > replace
cp replace /var/www/html/index.nginx-debian.html
rm replace
service nginx restart
