#!/usr/bin/env bash
# gives information about "holbertonschool" file
f=holbertonschool
if [ -e $f ]
then
    echo "holbertonschool file exists"
    if [ -f $f ]
    then
        echo "holbertonschool is a regular file"
    fi
    if [ -s $f ]
    then
        echo "holbertonschool file is not empty"
    else
        echo "holbertonschool file is empty"
    fi
else
    echo "holbertonschool file does not exist"
fi
