#!/usr/bin/env bash
# Configures an Ubuntu server with the parameters given
cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" >> ~/hosts.new
echo "8.8.8.8 facebook" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
