#!/usr/bin/env bash
# Fix this container so that Nginx run as the nginx user
pkill apache2
sed -i '/nginx.pid;/a user nginx;' /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chmod -R u+x /etc/nginx/
sudo -u nginx service nginx start
